name: Build

on:
  push:
  pull_request:
  release:
    types: [ published ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    name: Tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer update --no-ansi --no-interaction --no-progress
          composer global require php-coveralls/php-coveralls

      - name: Run tests
        run: XDEBUG_MODE=coverage vendor/bin/phpunit tests --coverage-clover=build/logs/clover.xml

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: ${{ matrix.php-version }}"
          COVERALLS_SERVICE_NAME: github
          COVERALLS_SERVICE_JOB_ID: "${{ github.run_id }}"
          COVERALLS_SERVICE_NUMBER: "${{ github.workflow }}-${{ github.run_number }}"
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: php-coveralls --coverage_clover=build/logs/clover.xml -v
